### PR TITLE
Frontend Login Infrastructure complete

### LINKED ISSUE #42: Add logo icon to Storybook
### Description

The favicon.ico of Rucio needs to be added as the default logo of Rucio into our Storybook. We need to integrate the same in our react app.

### Motivation

Currently, we rely on a URL fetch directly, which we want to avoid.

### Change

Replace the img tag with the Icon component.

### PR DESCRIPTION
**Pull request by nimishbongale**
Closes #42, #44 

- Switched out CSS for SCSS
- Use of primer + bulma hybrid SCSS
- More components
- Login flow complete from a frontend standpoint

image

### CODE REVIEW

**Comment by mlassnig** [comment]
May I suggest to have a third button "Username / Password" such that the two entry forms only pop up once you push that? 

Otherwise it might be a bit confusing (because one doesn't need to enter username/password for the other two options).

**Comment by nimishbongale** [comment]
> Otherwise it might be a bit confusing (because one doesn't need to enter username/password for the other two options).

Sure thing Mario, will update the PR with this logic 👍

**Comment by maany** [comment]
@nimishbongale could you rebase with master and update this PR, thanks :)

**Comment by nimishbongale** [comment]
> @nimishbongale could you rebase with master and update this PR, thanks :)

@maany, done!

**Review by maany — APPROVED** [review]

**Pull request merged**
